#!/usr/bin/env bash
# Build the freestanding wasm32+SIMD fill (scan-conversion) kernel and embed it
# as base64 TS. Same toolchain contract as the blur kernel: an LLVM clang that
# can emit+link wasm (wasm-ld on PATH or bundled). No emscripten runtime.
set -euo pipefail
cd "$(dirname "$0")"

CLANG="${WASM_CLANG:-}"
if [ -z "$CLANG" ]; then
  for c in \
    /opt/homebrew/Cellar/emscripten/*/libexec/llvm/bin/clang \
    "$(command -v clang || true)"; do
    if [ -x "$c" ] && [ -x "$(dirname "$c")/wasm-ld" ]; then CLANG="$c"; break; fi
  done
fi
if [ -z "$CLANG" ]; then echo "no wasm-capable clang (need clang + wasm-ld)"; exit 1; fi
export PATH="$(dirname "$CLANG"):$PATH"
echo "using clang: $CLANG"

"$CLANG" --target=wasm32 -O3 -msimd128 -nostdlib \
  -Wl,--no-entry -Wl,--export-dynamic -Wl,--export=__heap_base \
  -Wl,--initial-memory=1048576 -Wl,--max-memory=536870912 \
  -o fill.wasm fill.c

BYTES=$(wc -c < fill.wasm | tr -d ' ')
echo "fill.wasm: ${BYTES} bytes"

B64=$(base64 < fill.wasm | tr -d '\n')
cat > wasm-bytes.ts <<EOF
// AUTO-GENERATED by build.sh from fill.c. Do not edit by hand.
// Freestanding wasm32+SIMD fill scan-conversion kernel, base64-embedded.
export const FILL_WASM_BASE64 =
	"${B64}";
EOF
echo "wrote wasm-bytes.ts (${#B64} b64 chars)"
