#!/usr/bin/env bash
# Build the freestanding libass-compatible tiled rasterizer and embed it as
# base64 TypeScript. No Emscripten runtime is linked into the package.
set -euo pipefail
cd "$(dirname "$0")"

CLANG="${WASM_CLANG:-}"
if [ -z "$CLANG" ]; then
	for c in \
		/opt/homebrew/Cellar/emscripten/*/libexec/llvm/bin/clang \
		"$(command -v clang || true)"; do
		if [ -x "$c" ] && [ -x "$(dirname "$c")/wasm-ld" ]; then
			CLANG="$c"
			break
		fi
	done
fi
if [ -z "$CLANG" ]; then
	echo "no wasm-capable clang (need clang + wasm-ld)"
	exit 1
fi
export PATH="$(dirname "$CLANG"):$PATH"
echo "using clang: $CLANG"

"$CLANG" --target=wasm32 -O3 -msimd128 -nostdlib \
	-Wl,--no-entry -Wl,--export-dynamic -Wl,--export=__heap_base \
	-Wl,--initial-memory=1048576 -Wl,--max-memory=67108864 \
	-o ass-fill.wasm ass-fill.c

BYTES=$(wc -c < ass-fill.wasm | tr -d ' ')
echo "ass-fill.wasm: ${BYTES} bytes"

B64=$(base64 < ass-fill.wasm | tr -d '\n\\')
cat > wasm-bytes.ts <<EOF
// AUTO-GENERATED by build.sh from ass-fill.c. Do not edit by hand.
// Freestanding wasm32 libass-compatible tiled rasterizer, base64-embedded.
export const ASS_FILL_WASM_BASE64 =
	"${B64}";
EOF
echo "wrote wasm-bytes.ts (${#B64} b64 chars)"
